version: '3.4'
x-mysql-auth: &mysql-auth-vars
  MYSQL_USER: "interview_challenge"
  MYSQL_PASSWORD: hardtoGUESS45-
  MYSQL_DATABASE: employees

services:
  nginx:
    restart: always
    image: "nginx:1.15-alpine"
    volumes:
      - ./conf/nginx:/etc/nginx
    ports:
     - "8080:80"
  app:
    restart: always
    image: juanchimienti/interview_challenge:0.1.0
    build: .
    environment:
      <<: *mysql-auth-vars
      DB_HOST: "db"
  db:
    image: "mariadb:10.4"
    restart: always
    environment:
      <<: *mysql-auth-vars
      MYSQL_ROOT_PASSWORD: "SUPERhardpwd##"
    volumes:
      - ./data/mysql_live:/var/lib/mysql
      - ./data/initdb.d:/docker-entrypoint-initdb.d
